### ISSUE TITLE
I can't make it work, and i dont know why

### ISSUE THREAD

**Issue by psociety** [monomelodies/grunt-twig-gettext#4]
Sorry for taking some of your time, but i don't see what i'm doing wrong : (

File structure:
```bash
/var/www/gikla/
/var/www/gikla/Gruntfile.js
/var/www/gikla/locale/
/var/www/gikla/templates/index.html.twig
/var/www/gikla/templates/common/base.html.twig
/var/www/gikla/templates/common/ajax.html.twig
```

Gruntfile.js
```js
module.exports = function(grunt) {
    grunt.initConfig({
        twig_gettext: {
            options: {
                charset: 'UTF-8'
            },
            files: {
              'locale/en.po': ['templates/**/*.html.twig'],
            },
        }
      });

     grunt.loadNpmTasks('grunt-twig-gettext');
     grunt.registerTask('translate', ["twig_gettext"]);
```

Command:
```bash
psociety@ovh34678:/var/www/gikla$ grunt translate
Running "twig_gettext:files" (twig_gettext) task

Done, without errors.
```

`/locale/` folder remains empty and i don't see any execution error :(

I also tried `touch locale/en.po` but file remains at 0bytes after running the command.

**Comment by monomelodies** [comment]
could you send me the complete project so i can try to reproduce? tbh i
haven't looked at this for a while, but it worked last time i used it...


and, no problem at all :) 

On 11/08/2018 07:09 PM, psociety wrote: 

> Sorry for taking some of your time, but i don't see what i'm doing wrong : ( 
> 
> File structure:
> 
> /var/www/gikla/
> /var/www/gikla/Gruntfile.js
> /var/www/gikla/locale/
> /var/www/gikla/templates/index.html.twig
> /var/www/gikla/templates/common/base.html.twig
> /var/www/gikla/templates/common/ajax.html.twig
> 
> Gruntfile.js
> 
> module.exports = function(grunt) {
> grunt.initConfig({
> twig_gettext: {
> options: {
> charset: 'UTF-8'
> },
> files: {
> 'locale/en.po': ['templates/**/*.html.twig'],
> },
> }
> });
> 
> grunt.loadNpmTasks('grunt-twig-gettext');
> grunt.registerTask('translate', ["twig_gettext"]);
> 
> Command:
> 
> psociety@ovh34678:/var/www/gikla$ grunt translate
> Running "twig_gettext:files" (twig_gettext) task
> 
> Done, without errors.
> 
> /locale/ folder remains empty and i don't see any execution error :( 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

 

Links:
------
[1] https://github.com/monomelodies/grunt-twig-gettext/issues/4
[2]

**Comment by psociety** [comment]
I started debugging it.
https://github.com/monomelodies/grunt-twig-gettext/blob/master/tasks/twig_gettext.js#L20
At this point, if i do a `console.log(this.files);` returns an empty array. If i do `console.log(this);`:
```js
 { nameArgs: 'twig_gettext:files',
  name: 'twig_gettext',
  args: [],
  flags: {},
  async: [Function],
  errorCount: [Getter],
  requires: [Function: bound ],
  requiresConfig: [Function],
  options: [Function],
  target: 'files',
  data: {  'locale/en.po': ['templates/**/*.html.twig'] },
  files: [],
  filesSrc: [Getter] }
```
 **Edit:**

After checking your `Gruntfile.js`.
If i do (notice the attr custom_options):
```js
grunt.initConfig({
        twig_gettext: {
            custom_options: {
                options: {
                    charset: 'UTF-8'
                },
                files: {
                  'locale/en.po': ['templates/**/*.html.twig'],
                },
            }
        },
```


Rather than the demo code:
```js
grunt.initConfig({
        twig_gettext: {
            options: {
                charset: 'UTF-8'
            },
            files: {
              'locale/en.po': ['templates/**/*.html.twig'],
            },
        }
      });

```

It works.

```bash
Running "twig_gettext:custom_options" (twig_gettext) task
File "locale/en.po" created.

Done, without errors.
```

if i were you, i would also add an `if (this.files.length == 0) { console.info("No files received, doing nothing")}` or alike so people can see something is going wrong.

**Comment by monomelodies** [comment]
i'm going to dive into that tomorrow and will get back to you (it's
almost 11pm here now)

**Comment by monomelodies** [comment]
so, sorry. my head was with another project :) 

this is a multi-task, so you also need to specify a target. E.g.: 

grunt.initConfig({
        twig_gettext: {
            EXAMPLE: {
                options: {
                    charset: 'UTF-8'
                },
                files: {
                    'locale/en.po': ['templates/**/*.html.twig'],
                }
            }
        }
    }); 

On 11/09/2018 09:44 PM, psociety wrote: 

> I started debugging it.
> https://github.com/monomelodies/grunt-twig-gettext/blob/master/tasks/twig_gettext.js#L20
> At this point, if i do a console.log(this.files); returns an empty array. If i do console.log(this);:
> 
> { nameArgs: 'twig_gettext:files',
> name: 'twig_gettext',
> args: [],
> flags: {},
> async: [Function],
> errorCount: [Getter],
> requires: [Function: bound ],
> requiresConfig: [Function],
> options: [Function],
> target: 'files',
> data: {  'locale/en.po': ['templates/**/*.html.twig'] },
> files: [],
> filesSrc: [Getter] }
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

 

Links:
------
[1]
https://github.com/monomelodies/grunt-twig-gettext/issues/4#issuecomment-437489620
[2]

**Comment by psociety** [comment]
I understand, but if you check your example in the README, you will see that you set TARGET instead of files attr rather than as parent object:
https://github.com/monomelodies/grunt-twig-gettext#the-twig_gettext-task

So project is working fine, examples are not.

**Comment by monomelodies** [comment]
thanks for bringing that to my attention, i corrected it in the latest
version (0.3.2) 

On 11/10/2018 09:12 AM, psociety wrote: 

> I understand, but if you check your example in the README, you will see that you set TARGET instead of files attr rather than as parent object:
> https://github.com/monomelodies/grunt-twig-gettext#the-twig_gettext-task 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

 

Links:
------
[1]
https://github.com/monomelodies/grunt-twig-gettext/issues/4#issuecomment-437567018
[2]
